import { useCallback, useEffect, useRef, useState } from 'react'
import { registerSW } from 'virtual:pwa-register'

// Re-check for a new build every 30 min while the tab stays open (plus on each refocus).
const UPDATE_POLL_MS = 30 * 60 * 1000

export interface SwState {
  /** a new build has been downloaded and is waiting to activate */
  needRefresh: boolean
  /** the app shell has been precached and works offline */
  offlineReady: boolean
  /** true while a manual update check is in flight (drives the button spinner) */
  checking: boolean
  /** apply the waiting service worker and reload to the new build */
  reload: () => void
  /** manual "check for updates" — pings the server for a new service worker */
  checkForUpdate: () => Promise<void>
}

/**
 * Registers the service worker (generated by vite-plugin-pwa) with a prompt-style update flow:
 * checks at startup, on an interval, and whenever the tab regains focus. Exposes `needRefresh`
 * (drives the banner), a manual `checkForUpdate`, and `reload` to activate the new build.
 *
 * Mount exactly once — via <SwProvider> — so the SW isn't registered twice.
 */
export function useServiceWorker(): SwState {
  const [needRefresh, setNeedRefresh] = useState(false)
  const [offlineReady, setOfflineReady] = useState(false)
  const [checking, setChecking] = useState(false)
  const registrationRef = useRef<ServiceWorkerRegistration | undefined>(undefined)
  const updateSWRef = useRef<((reloadPage?: boolean) => Promise<void>) | undefined>(undefined)

  useEffect(() => {
    let intervalId: ReturnType<typeof setInterval> | undefined
    const onVisible = () => {
      if (document.visibilityState === 'visible') void registrationRef.current?.update()
    }

    updateSWRef.current = registerSW({
      // Register now — this effect already runs after `load`, so don't defer to the load event.
      immediate: true,
      onNeedRefresh() {
        setNeedRefresh(true)
      },
      onOfflineReady() {
        setOfflineReady(true)
      },
      onRegisteredSW(_swScriptUrl, registration) {
        registrationRef.current = registration
        if (!registration) return
        // (a) check once now (covers a long-lived returning tab)…
        void registration.update()
        // (b) …then on an interval (skip while installing / offline)…
        intervalId = setInterval(() => {
          if (registration.installing || !navigator.onLine) return
          void registration.update()
        }, UPDATE_POLL_MS)
        // (c) …and whenever the tab regains focus.
        document.addEventListener('visibilitychange', onVisible)
      },
      onRegisterError(error) {
        console.error('[pwa] service worker registration failed', error)
      },
    })

    return () => {
      if (intervalId) clearInterval(intervalId)
      document.removeEventListener('visibilitychange', onVisible)
    }
  }, [])

  const reload = useCallback(() => {
    void updateSWRef.current?.(true)
  }, [])

  const checkForUpdate = useCallback(async () => {
    setChecking(true)
    try {
      await registrationRef.current?.update()
    } catch (error) {
      console.error('[pwa] update check failed', error)
    } finally {
      // keep the spinner perceptible; needRefresh flips via onNeedRefresh if a new build was found
      setTimeout(() => setChecking(false), 600)
    }
  }, [])

  return { needRefresh, offlineReady, checking, reload, checkForUpdate }
}
